import img1 from '../assets/images/Becoming Belgium - consultancy and communications company.jpeg'
import img2 from '../assets/images/Co enzyme Q10 Packaging Design.jpeg'
import img3 from '../assets/images/Dr_ Paleps.jpeg'
import img4 from '../assets/images/Facewash Tube with Box.jpeg'
import img5 from '../assets/images/GLUTATHION DR_LACIR DESIGN PACKAGING _ THIET KE BAO BI - VICTOR TRAN ✪.jpeg'
import img6 from '../assets/images/Glutathione Packaging Design.jpeg'
import img7 from '../assets/images/Herbal tea packaging.jpeg'
import img8 from '../assets/images/If anything, the name will kill its potential success_.jpeg'
import img9 from '../assets/images/Male & Female Fertility Product.jpeg'
import img10 from '../assets/images/download (1).jpeg'
import img11 from '../assets/images/download (2).jpeg'
import img12 from '../assets/images/download.jpeg'
// {
//     id:1,
//     image:{},
//     discount:`${'30%'} off`,
//     name: 'Almond oil 120 ml Bottle',
//     type: 'oil',
//     packSize:'70ml',
//     discountPrice:'560',
//     originalPrice:'860',
//     company:'',
//     category:'',
//     btnText:'Add to Cart',
// },
export const productCards = [
  {
    id: 1,
    image: img1,
    discount: "20% off",
    name: "Paracetamol 500mg Tablet",
    type: "tablet",
    packSize: "10 tablets",
    discountPrice: "80",
    originalPrice: "100",
    company: "PharmaPlus",
    category: "Medicines",
    description: "Paracetamol is widely used for relief from fever and mild to moderate pain. It works by lowering chemicals in the brain that cause pain and fever. The medicine is safe for most people when used in recommended doses. Overdose, however, may cause serious liver damage and should be avoided.",
    dosage: "1–2 tablets every 6 hours, not exceeding 8 tablets in 24 hours.",
    sideEffects: "May cause nausea, allergic reactions, or liver damage with overdose.",
    prescriptionRequired: false,
    quantity: '20',
    btnText: "Add to Cart",
  },
  {
    id: 2,
    image: img2,
    discount: "15% off",
    name: "Amoxicillin 250mg Capsule",
    type: "capsule",
    packSize: "20 capsules",
    discountPrice: "170",
    originalPrice: "200",
    company: "HealthCare Ltd",
    category: "Health Care",
    description: "Amoxicillin is an antibiotic used to treat a wide range of bacterial infections. It works by preventing the bacteria from forming protective cell walls, making them easier to kill. It is commonly prescribed for throat, chest, ear, and urinary infections. This medicine should always be taken as directed by a healthcare professional.",
    dosage: "1 capsule every 8 hours for 5–7 days, as prescribed by doctor.",
    sideEffects: "Diarrhea, rash, nausea, or allergic reaction.",
    prescriptionRequired: true,
    quantity: '20',
    btnText: "Add to Cart",
  },
  {
    id: 3,
    image: img3,
    discount: "10% off",
    name: "Vitamin C 500mg Tablet",
    type: "tablet",
    packSize: "30 tablets",
    discountPrice: "270",
    originalPrice: "300",
    company: "NutriLife",
    category: "Supplements",
    description: "Vitamin C is an essential nutrient that strengthens the immune system and protects the body from free radicals. It supports skin health by boosting collagen production. Regular intake helps reduce fatigue, prevents infections, and speeds up recovery from colds. It is suitable for daily use as part of a balanced lifestyle.",
    dosage: "1 tablet daily after meal.",
    sideEffects: "May cause stomach upset or kidney stones in high doses.",
    prescriptionRequired: false,
    quantity: '20',
    btnText: "Add to Cart",
  },
  {
    id: 4,
    image: img4,
    discount: "25% off",
    name: "Cough Syrup 120ml",
    type: "syrup",
    packSize: "120ml",
    discountPrice: "150",
    originalPrice: "200",
    company: "MediCure",
    category: "Wellness",
    description: "This cough syrup provides effective relief from dry, irritating coughs. It works by soothing the throat lining and reducing the urge to cough. It can also ease breathing difficulties caused by throat irritation. Regular use as recommended helps improve sleep and comfort during cold or flu.",
    dosage: "10ml three times daily after meals.",
    sideEffects: "Drowsiness, mild dizziness, or stomach upset.",
    prescriptionRequired: false,
    quantity: '20',
    btnText: "Add to Cart",
  },
  {
    id: 5,
    image: img5,
    discount: "30% off",
    name: "Aspirin 75mg Tablet",
    type: "tablet",
    packSize: "14 tablets",
    discountPrice: "70",
    originalPrice: "100",
    company: "PharmaWell",
    category: "Medicines",
    description: "Aspirin 75mg is widely used as a blood thinner and pain reliever. It helps reduce the risk of heart attacks and strokes by preventing blood clots. It also provides relief from headaches, muscle aches, and fever. Regular use should be monitored by a doctor to avoid complications.",
    dosage: "1 tablet daily, preferably after meal.",
    sideEffects: "Stomach irritation, bleeding risk, or allergic reaction.",
    prescriptionRequired: true,
    quantity: '20',
    btnText: "Add to Cart",
  },
  {
    id: 6,
    image: img6,
    discount: "30% off",
    name: "Almond oil 120 ml Bottle",
    type: "oil",
    packSize: "120ml",
    discountPrice: "560",
    originalPrice: "860",
    company: "ABC Pharma",
    category: "Personal Care",
    description: "Almond oil is a natural product used for skin and hair care. It deeply moisturizes dry skin, strengthens hair roots, and adds shine. The oil is rich in Vitamin E and fatty acids that promote healthy growth. It is gentle enough for daily use and suitable for massage purposes.",
    dosage: "Apply small amount on skin or hair as needed.",
    sideEffects: "Generally safe, may cause allergic reaction in sensitive users.",
    prescriptionRequired: false,
    quantity: '20',
    btnText: "Add to Cart",
  },
  {
    id: 7,
    image: img7,
    discount: "15% off",
    name: "Paracetamol 500mg Tablets",
    type: "tablet",
    packSize: "20 tablets",
    discountPrice: "85",
    originalPrice: "100",
    company: "XYZ Pharma",
    category: "Medicines",
    description: "Paracetamol is a trusted medicine for pain relief and fever reduction. It works by lowering chemicals that trigger fever and discomfort. It is suitable for use in common cold, flu, headache, or body aches. Safe when taken in recommended dosage, but overdosing may damage the liver.",
    dosage: "1 tablet every 6 hours if required, not exceeding daily limit.",
    sideEffects: "Liver damage on overdose, mild nausea.",
    prescriptionRequired: false,
    quantity: '20',
    btnText: "Add to Cart",
  },
  {
    id: 8,
    image: img8,
    discount: "10% off",
    name: "Vitamin C 1000mg",
    type: "tablet",
    packSize: "30 tablets",
    discountPrice: "450",
    originalPrice: "500",
    company: "HealthPlus",
    category: "Supplements",
    description: "Vitamin C 1000mg provides high-strength antioxidant protection. It helps boost immunity, support collagen production, and protect cells from damage. This supplement is useful for people with high stress or poor diet. Daily use keeps the body energized and resistant against infections.",
    dosage: "1 tablet per day with water.",
    sideEffects: "May cause diarrhea or nausea in sensitive people.",
    prescriptionRequired: false,
    quantity: '20',
    btnText: "Add to Cart",
  },
  {
    id: 9,
    image: img9,
    discount: "20% off",
    name: "Cough Syrup 120ml",
    type: "syrup",
    packSize: "120ml",
    discountPrice: "120",
    originalPrice: "150",
    company: "MediCare",
    category: "Organic",
    description: "This herbal-based cough syrup provides natural relief from cough and sore throat. It contains soothing ingredients that calm irritation and reduce coughing. It is especially useful during seasonal changes and mild throat infections. Safe for both adults and children when used as directed.",
    dosage: "10ml twice a day or as directed.",
    sideEffects: "Minimal, may cause mild stomach upset.",
    prescriptionRequired: false,
    quantity: '20',
    btnText: "Add to Cart",
  },
  {
    id: 10,
    image: img10,
    discount: "25% off",
    name: "Ibuprofen 400mg",
    type: "tablet",
    packSize: "10 tablets",
    discountPrice: "150",
    originalPrice: "200",
    company: "PharmaLife",
    category: "Medicines",
    description: "Ibuprofen is a non-steroidal anti-inflammatory drug (NSAID) that reduces pain and inflammation. It is commonly used for headaches, muscle pain, arthritis, and menstrual cramps. The medicine also helps reduce fever and swelling. Prolonged use should be monitored to avoid stomach problems.",
    dosage: "1 tablet every 6–8 hours as needed.",
    sideEffects: "Stomach upset, dizziness, or risk of ulcers.",
    prescriptionRequired: true,
    quantity: '20',
    btnText: "Add to Cart",
  },
  {
    id: 11,
    image: img11,
    discount: "12% off",
    name: "Vitamin D3 Drops",
    type: "drops",
    packSize: "15ml",
    discountPrice: "220",
    originalPrice: "250",
    company: "NutriCare",
    category: "Baby Care",
    description: "Vitamin D3 drops are essential for healthy bone growth and immunity in babies. They help the body absorb calcium and phosphorus, strengthening teeth and bones. These drops are often recommended for infants not getting enough sunlight. Safe, gentle, and easy to give daily.",
    dosage: "5 drops daily or as directed by pediatrician.",
    sideEffects: "Very rare, may cause nausea or constipation.",
    prescriptionRequired: false,
    quantity: '20',
    btnText: "Add to Cart",
  },
  {
    id: 12,
    image: img12,
    discount: "18% off",
    name: "Aspirin 300mg",
    type: "tablet",
    packSize: "14 tablets",
    discountPrice: "110",
    originalPrice: "135",
    company: "MediTrust",
    category: "Medicines",
    description: "Aspirin 300mg is used for pain relief and reducing the risk of heart attack or stroke. It works by thinning the blood and preventing clot formation. The medicine also provides relief from fever, headaches, and mild inflammation. It should be taken under medical supervision for heart patients.",
    dosage: "1 tablet daily or as advised by doctor.",
    sideEffects: "Stomach bleeding, nausea, dizziness.",
    prescriptionRequired: true,
    quantity: '20',
    btnText: "Add to Cart",
  },
];


export const orders = [
  {
    id: "ORD123",
    date: "2025-08-15",
    total: 4500,
    status: "Delivered",
    items: [
      { name: "Paracetamol 500mg", qty: 2, price: 200 },
      { name: "Vitamin C Tablets", qty: 1, price: 1500 },
    ],
    shipping: {
      name: "Syeda Mahnoor",
      address: "123 Main Street, RYK, Pakistan",
      phone: "+92 300 1234567",
    },
    payment: "Cash on Delivery",
  },
  {
    id: "ORD124",
    date: "2025-08-20",
    total: 2200,
    status: "Shipped",
    items: [
      { name: "Blood Pressure Monitor", qty: 1, price: 2200 },
    ],
    shipping: {
      name: "Syeda Mahnoor",
      address: "123 Main Street, RYK, Pakistan",
      phone: "+92 300 1234567",
    },
    payment: "JazzCash",
  },
];


